### Get Index Page
GET http://localhost:8080/asdf/index

### Get Feed
GET http://localhost:8080/asdf/feed

### Get Admin Page
GET http://localhost:8080/asdf/admin

### Get Individual Gallery
GET http://localhost:8080/gallery/oi7o

### Search Movie Poster (TMDB)
GET http://localhost:8080/asdf/admin/api/search-movie-poster?movieTitle=Inception

### Generate Thumbnail (SSE stream)
GET http://localhost:8080/asdf/admin/api/generate-thumbnail?videoPath=Movies/Movies/Inception.m4v&timeMs=5000

### Fetch Movie Poster (SSE stream)
GET http://localhost:8080/asdf/admin/api/fetch-movie-poster?videoPath=Movies/Movies/Inception.m4v

### Clear Thumbnail
POST http://localhost:8080/asdf/admin/api/clear-thumbnail
Content-Type: application/json

{
  "thumbnailPath": "Movies/Movies/Inception.jpg"
}

### Bulk Generate Thumbnails
POST http://localhost:8080/asdf/admin/api/bulk-generate-thumbnails
Content-Type: application/json

{
  "videoPaths": [
    "Movies/Movies/Movie1.m4v",
    "Movies/Movies/Movie2.m4v"
  ],
  "timeMs": 5000,
  "maxParallel": 3
}

### Bulk Clear Thumbnails
POST http://localhost:8080/asdf/admin/api/bulk-clear-thumbnails
Content-Type: application/json

{
  "thumbnailPaths": [
    "Movies/Movies/Movie1.jpg",
    "Movies/Movies/Movie2.jpg"
  ]
}

